### ISSUE TITLE
Dockerize GAM + Revisit

### ISSUE THREAD

**Issue by dominikgeissler** [sbsev/google-workspace#14]
This repo seems like it wasn't used recently and I'm not entirely sure whether the tools are used, which is sad! I would dockerize the GAM in order to make it easier for non-techies to use the GAMs possibilities as well as revisit some of the already existing doc + material.

**Comment by janosh** [comment]
Maybe check with @kleinicke if anyone still uses GAM or wants to in the future. If not, we can sunset this.

**Comment by dominikgeissler** [comment]
@janosh I'm currently working on making the GAM more accessible. One question: Is there a reason that there are file dupes (e.g. logos)? Do these PDFs also need to be in the repo?

**Comment by janosh** [comment]
I think the file duplicates were due to our email signatures hard-coding the links to these images. So removing them would break the logos below some of our older emails. Not important if you ask me. Feel free to delete.

**Comment by dominikgeissler** [comment]
@janosh do you know why I get a 403 response? My local GAM-instance works except for signature changes (also 403). Help would be appreciated <3 

![image](https://github.com/sbsev/google-workspace/assets/39053640/6557bbb5-3125-4298-b7e1-c58becb9a548)
![image](https://github.com/sbsev/google-workspace/assets/39053640/ab02b5c9-278e-4f14-a34f-dc018521fd37)

**Comment by dominikgeissler** [comment]
@janosh works, thanks! ❤️

**Comment by dominikgeissler** [comment]
Now I still have the following error when trying to set the signature of an account

```
ERROR: User <...>@studenten-bilden-schueler.de: unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.
```

Do you know this error?

**Comment by janosh** [comment]
Sounds like you didn't finish setting up all necessary GAM scopes? Maybe log out of GAM and start from scratch?

**Comment by dominikgeissler** [comment]
I tried from scratch and still get the same error. Weird...

**Comment by dominikgeissler** [comment]
I'm trying this inside a docker container, my command:

```console
$> /root/bin/gam/gam user dominik.geissler signature file ../gmail/signatures/board.html html replace firstName Dominik replace lastName Geißler replace department Bundesvorstand replace jobtitle IT

ERROR: User dominik.geissler@studenten-bilden-schueler.de: unauthorized_client: Client is unauthorized to retrieve access tokens using this method, or client not authorized for any of the scopes requested.
```
I have selected all scopes, authorized client & project. The rest (e.g. creation of accounts, adding to groups, ...) works, however signatures seem to be a problem

**Comment by janosh** [comment]
What do you get?

```sh
gam user dominik.geissler check serviceaccount
```

**Comment by dominikgeissler** [comment]
@janosh ah awesome, some of the delegated scopes weren't selected, didn't know i had to set those. Now the signature also works, tysm!

**Comment by dominikgeissler** [comment]
done
